// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PAS.DBContext;

#nullable disable

namespace PAS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221143736_ApplicatorLicense")]
    partial class ApplicatorLicense
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ChargeInterest")
                        .HasColumnType("boolean");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceChemicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceGroupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InvoicePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InvoiceRatePerAcre")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceUnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGroupSelected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuoteInventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceGroupId");

                    b.HasIndex("QuoteInventoryId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LoadFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FieldAcres")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FieldAverageRate")
                        .HasColumnType("numeric");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FieldTotalGallons")
                        .HasColumnType("numeric");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("LoadMixId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedFieldId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoadMixId");

                    b.ToTable("LoadFields");
                });

            modelBuilder.Entity("PAS.Models.ApplicatorLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrintOnInvoice")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ApplicatorLicenses");
                });

            modelBuilder.Entity("PAS.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerBusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerCell")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerFName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerFax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerLName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultInterestRate")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PAS.Models.CustomerField", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InvoiceSplit")
                        .HasColumnType("numeric");

                    b.HasKey("CustomerId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("CustomerField", (string)null);
                });

            modelBuilder.Entity("PAS.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Acres")
                        .HasColumnType("double precision");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("PAS.Models.InvoiceHeader", b =>
                {
                    b.Property<int>("InvoiceGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceGroupId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceGroupId");

                    b.HasIndex("CustomerId");

                    b.ToTable("InvoiceHeaders");
                });

            modelBuilder.Entity("PAS.Models.LoadMix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Crop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LMRatePerAcre")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoadMixId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("LoadTime")
                        .HasColumnType("interval");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcres")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGallons")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("LoadMixes");
                });

            modelBuilder.Entity("PAS.Models.LoadMixDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EPA")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("LoadMixId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("QuotePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("QuoteUnitOfMeasure")
                        .HasColumnType("text");

                    b.Property<string>("RatePerAcre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoadMixId");

                    b.ToTable("LoadMixDetails");
                });

            modelBuilder.Entity("PAS.Models.NoQuoteInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceChemicalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InvoiceCustomer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("InvoicePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InvoiceRatePerAcre")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsGroupSelected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("NoQuoteInvoices");
                });

            modelBuilder.Entity("PAS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultUnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EPA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WeightedAveragePrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PAS.Models.ProductPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProductPurchases");
                });

            modelBuilder.Entity("PAS.Models.ProductVendor", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "VendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProductVendors");
                });

            modelBuilder.Entity("PAS.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeliveryPickUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PickUpLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("PAS.Models.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EPANumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewQuantityReceived")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductEPA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductUOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityUnreceived")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasurePurchase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("PAS.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerBusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedAcres")
                        .HasColumnType("numeric");

                    b.Property<string>("QuoteCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("QuoteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuotePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuoteTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("QuoteZipcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("PAS.Models.QuoteInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChemicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EPA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityPerAcre")
                        .HasColumnType("numeric");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuotePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("QuoteUnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValueSql("gen_random_bytes(8)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteInventories");
                });

            modelBuilder.Entity("PAS.Models.UOMConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CFPurSold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("PUOM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QUOM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SUOM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UOMConversions");
                });

            modelBuilder.Entity("PAS.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesRepEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesRepPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceGroupId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Invoice", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.InvoiceHeader", "InvoiceHeader")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.QuoteInventory", "QuoteInventory")
                        .WithMany("Invoices")
                        .HasForeignKey("QuoteInventoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("InvoiceHeader");

                    b.Navigation("QuoteInventory");
                });

            modelBuilder.Entity("LoadFields", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAS.Models.LoadMix", "LoadMix")
                        .WithMany("LoadFields")
                        .HasForeignKey("LoadMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoadMix");
                });

            modelBuilder.Entity("PAS.Models.CustomerField", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("CustomerFields")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.Field", "Field")
                        .WithMany("CustomerFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("PAS.Models.Field", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("Fields")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PAS.Models.InvoiceHeader", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PAS.Models.LoadMix", b =>
                {
                    b.HasOne("PAS.Models.Quote", "Quote")
                        .WithMany("LoadMixes")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("PAS.Models.LoadMixDetails", b =>
                {
                    b.HasOne("PAS.Models.LoadMix", "LoadMix")
                        .WithMany("LoadMixDetails")
                        .HasForeignKey("LoadMixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadMix");
                });

            modelBuilder.Entity("PAS.Models.NoQuoteInvoice", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("NoQuoteInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PAS.Models.ProductPurchase", b =>
                {
                    b.HasOne("PAS.Models.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PAS.Models.ProductVendor", b =>
                {
                    b.HasOne("PAS.Models.Product", "Product")
                        .WithMany("ProductVendors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.Vendor", "Vendor")
                        .WithMany("ProductVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PAS.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PAS.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PAS.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("PAS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("PAS.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PAS.Models.Quote", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("Quotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PAS.Models.QuoteInventory", b =>
                {
                    b.HasOne("PAS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("PAS.Models.Quote", "Quote")
                        .WithMany("QuoteInventories")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("PAS.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PAS.Models.InvoiceHeader", "InvoiceHeader")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("InvoiceHeader");
                });

            modelBuilder.Entity("PAS.Models.Customer", b =>
                {
                    b.Navigation("CustomerFields");

                    b.Navigation("Fields");

                    b.Navigation("Invoices");

                    b.Navigation("NoQuoteInvoices");

                    b.Navigation("Payments");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("PAS.Models.Field", b =>
                {
                    b.Navigation("CustomerFields");
                });

            modelBuilder.Entity("PAS.Models.InvoiceHeader", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PAS.Models.LoadMix", b =>
                {
                    b.Navigation("LoadFields");

                    b.Navigation("LoadMixDetails");
                });

            modelBuilder.Entity("PAS.Models.Product", b =>
                {
                    b.Navigation("ProductVendors");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("PAS.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PAS.Models.Quote", b =>
                {
                    b.Navigation("LoadMixes");

                    b.Navigation("QuoteInventories");
                });

            modelBuilder.Entity("PAS.Models.QuoteInventory", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("PAS.Models.Vendor", b =>
                {
                    b.Navigation("ProductVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
